sap:
  btp:
    credstore:
      namespace: credstore-runny-time
      encrypted: false
      username: <replaced_by_cfenv>
      password: <replaced_by_cfenv>
      url: <replaced_by_cfenv>
      clientPrivateKey: <replaced_by_cfenv>
      serverPublicKey: <replaced_by_cfenv>
