on:
  push:
    paths: 
      - k8s/dev_deployment.yaml

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
    - uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.DEV_KUBECONFIG }}
        command: apply -n dgca-test -f ./k8s/dev_deployment.yaml
  
